# -*- coding: utf-8 -*-
"""Hackbio-stage1-reproduce figure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bSJgKVNJ6xRH6TuJroSVmnKp8X4OLKPK

Part A – Gene Expression Analysis

a. Heatmap

Use the normalized gene expression dataset to plot a clustered heatmap of the top differentially expressed genes between HBR and UHR samples.
Label both genes and samples.
Use a color gradient (e.g., Blues) to indicate expression levels.
"""

# Install seaborn if needed
!pip install seaborn

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# ============================
# 1. Load Your Normalized Counts
# ============================
# Example: if uploaded to Colab via "Files" panel
df = pd.read_csv("hbr_uhr_top_deg_normalized_counts.csv", index_col=0)

# If TSV:
# df = pd.read_csv("hbr_uhr_top_deg_normalized_counts.tsv", sep="\t", index_col=0)

print("Data loaded. Shape:", df.shape)
df.head()

plt.figure(figsize=(10, 12))

sns.clustermap(
    df,
    cmap="Blues",          # color gradient
    linewidths=0.5,
    figsize=(10, 12),
    row_cluster=True,      # cluster genes
    col_cluster=True,      # cluster samples
)

plt.title("Clustered Heatmap of Top DEGs (HBR vs UHR)")
plt.show()

"""b. Volcano Plot

Plot log2FoldChange vs log10(Padj) from the DEG results.
Color points by significance:
Upregulated: green
Downregulated: orange
Not significant: grey
Add dashed vertical lines at log2FoldChange = ±1.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load your differential expression results
# Example: If uploaded to Colab as a CSV
hbr_uhr_deg_chr22_with_significance = pd.read_csv("hbr_uhr_deg_chr22_with_significance.csv")

df = hbr_uhr_deg_chr22_with_significance.copy()

# Replace zero or NA padj values (log10 undefined)
df['PAdj'] = df['PAdj'].replace(0, 1e-300)
df['PAdj'] = df['PAdj'].fillna(1.0)

# Compute -log10(padj)
df['-log10PAdj'] = -np.log10(df['PAdj'])

# Categorize gene significance
def get_category(row):
    if row['PAdj'] < 0.05:
        if row['log2FoldChange'] >= 1:
            return "Upregulated"
        elif row['log2FoldChange'] <= -1:
            return "Downregulated"
    return "Not significant"

df['category'] = df.apply(get_category, axis=1)

# Colors for categories
colors = {
    "Upregulated": "green",
    "Downregulated": "orange",
    "Not significant": "grey"
}

# Plot
plt.figure(figsize=(10, 7))
for category, color in colors.items():
    subset = df[df['category'] == category]
    plt.scatter(subset['log2FoldChange'],
                subset['-log10PAdj'],
                c=color,
                label=category,
                alpha=0.7,
                s=30)

# Add significance lines
plt.axvline(x=1, color='black', linestyle='--', linewidth=1)
plt.axvline(x=-1, color='black', linestyle='--', linewidth=1)
plt.axhline(y=-np.log10(0.05), color='black', linestyle='--', linewidth=1)

# Labels and title
plt.xlabel('log2(Fold Change)', fontsize=14)
plt.ylabel('-log10(PAdj)', fontsize=14)
plt.title('Volcano Plot: HBR vs UHR (Chr22)', fontsize=16)

plt.legend()
plt.tight_layout()
plt.show()

"""Part B – Breast Cancer Data Exploration

c. Scatter Plot (radius vs texture)

Plot texture_mean vs radius_mean and color points by diagnosis (M = malignant, B = benign).

d. Correlation Heatmap

Compute the correlation matrix of six key features:

radius_mean, texture_mean, perimeter_mean, area_mean, smoothness_mean, compactness_mean.

Plot as a heatmap with correlation values annotated.

e. Scatter Plot (smoothness vs compactness)

Plot compactness_mean vs smoothness_mean colored by diagnosis.
Include gridlines and clear axis labels.

f. Density Plot (area distribution)

Plot kernel density estimates (KDE) of area_mean for both M and B diagnoses on the same axis.
Add legend and labeled axes.
"""

import pandas as pd

df = pd.read_csv("data-3.csv")

df.head()

"""C. Scatter Plot – radius_mean vs texture_mean (colored by diagnosis)"""

import matplotlib.pyplot as plt

plt.figure(figsize=(7,5))

colors = {'M': 'red', 'B': 'blue'}

for diag in df['diagnosis'].unique():
    subset = df[df['diagnosis'] == diag]
    plt.scatter(subset['radius_mean'], subset['texture_mean'],
                c=colors[diag], label=('Malignant' if diag=='M' else 'Benign'),
                alpha=0.7)

plt.xlabel("Radius Mean")
plt.ylabel("Texture Mean")
plt.title("Radius vs Texture (Colored by Diagnosis)")
plt.legend()
plt.grid(True)
plt.show()

"""D. Correlation Heatmap – 6 Key Features

"""

import seaborn as sns
import matplotlib.pyplot as plt

features = [
    "radius_mean",
    "texture_mean",
    "perimeter_mean",
    "area_mean",
    "smoothness_mean",
    "compactness_mean"
]

corr_matrix = df[features].corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap of Key Breast Cancer Features")
plt.show()

"""E. Scatter Plot – smoothness_mean vs compactness_mean"""

plt.figure(figsize=(7,5))

for diag in df['diagnosis'].unique():
    subset = df[df['diagnosis'] == diag]
    plt.scatter(subset['smoothness_mean'], subset['compactness_mean'],
                c=colors[diag], label=('Malignant' if diag=='M' else 'Benign'),
                alpha=0.7)

plt.xlabel("Smoothness Mean")
plt.ylabel("Compactness Mean")
plt.title("Smoothness vs Compactness (Colored by Diagnosis)")
plt.grid(True)
plt.legend()
plt.show()

"""F. Density Plot – area_mean distribution (M vs B)"""

import seaborn as sns

plt.figure(figsize=(8,5))

sns.kdeplot(df[df['diagnosis']=="M"]['area_mean'], label="Malignant", shade=True)
sns.kdeplot(df[df['diagnosis']=="B"]['area_mean'], label="Benign", shade=True)

plt.xlabel("Area Mean")
plt.ylabel("Density")
plt.title("Density Plot of Area Mean (Malignant vs Benign)")
plt.legend()
plt.show()